version: "3.0"

services:
  itsapark_challenge:
    build: .
    container_name: ITSAPARK_CHALLENGE
    restart: always
    tty: true
    volumes:
      - .:/app
      - /app/node_modules/
    ports:
      - 3010:3000
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "5"
